/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import java.awt.Color;
import java.io.IOException;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author gerosa_simone
 */
public class Form2 extends javax.swing.JFrame {

    static Form2 f;
    Chat c;
    Comunicazione c1;

    /**
     * Creates new form Form2
     */
    public Form2() throws SocketException {
        initComponents();
        f=this;
        c = Chat.getInstance();
        
    }

     public static synchronized Form2 Singleton() throws SocketException {
        if (f == null) {
            f = new Form2();
        }

        return f;

    }

    public void setRicezione(Comunicazione a) throws SocketException {
        c = Chat.getInstance();
        this.c1 = a;
        c.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        TxtMessaggio = new javax.swing.JTextField();
        Invia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Invia.setText("Invia");
        Invia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InviaMouseClicked(evt);
            }
        });
        Invia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TxtMessaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Invia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtMessaggio)
                    .addComponent(Invia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InviaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InviaMouseClicked
        if (TxtMessaggio.getText() != "") {
            try {
                // TODO add your handling code here:
                c1.InviaMessaggio(TxtMessaggio.getText());
                TxtMessaggio.setText("");
            } catch (IOException ex) {
                Logger.getLogger(Form2.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_InviaMouseClicked

    private void InviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InviaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InviaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setPersona(String s) {
        Nome.setText(s);
    }

    public void AggiungiDestra(String s, int y, int altezza) {
        JLabel l = new JLabel();
        l.setBounds(200, y, 200, altezza);
        l.setText(s);
        l.setBackground(Color.GREEN);
        this.add(l);
    }

    public void AggiungiSinistra(String s, int y, int altezza) {
        JLabel l = new JLabel();
        l.setBounds(0, y, 200, altezza);
        l.setText(s);
        l.setBackground(Color.LIGHT_GRAY);
        this.add(l);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Invia;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField TxtMessaggio;
    // End of variables declaration//GEN-END:variables
}
